// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using siades.Database.DataContext;

#nullable disable

namespace siades.Database.Persistence
{
    [DbContext(typeof(SiadesDbContext))]
    [Migration("20230808143610_Review 4")]
    partial class Review4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("siades.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GetTownShiepId")
                        .HasColumnType("int");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NeighborHud")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GetTownShiepId");

                    b.ToTable("Tb_Address");
                });

            modelBuilder.Entity("siades.Models.Blood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloodGroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BloodGroupName")
                        .IsUnique();

                    b.ToTable("Tb_Blood");
                });

            modelBuilder.Entity("siades.Models.BloodRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiseasedAge")
                        .HasColumnType("int");

                    b.Property<string>("DiseasedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("GetBloodId")
                        .HasColumnType("int");

                    b.Property<int?>("GetDonorId")
                        .HasColumnType("int");

                    b.Property<int?>("GetHospitalId")
                        .HasColumnType("int");

                    b.Property<bool>("HasFamDonor")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAcepted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHomeDonor")
                        .HasColumnType("bit");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GetBloodId");

                    b.HasIndex("GetDonorId");

                    b.HasIndex("GetHospitalId");

                    b.ToTable("Tb_BloodRequest");
                });

            modelBuilder.Entity("siades.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAdrress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("HousePhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumeber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tb_Contact");
                });

            modelBuilder.Entity("siades.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryName")
                        .IsUnique();

                    b.HasIndex("PhoneCode")
                        .IsUnique();

                    b.ToTable("Tb_Country");
                });

            modelBuilder.Entity("siades.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloodGroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GetPersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BloodGroupName")
                        .IsUnique();

                    b.HasIndex("GetPersonId");

                    b.ToTable("Tb_Doctor");
                });

            modelBuilder.Entity("siades.Models.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BloodGroup")
                        .IsUnique();

                    b.HasIndex("DonorId");

                    b.ToTable("Tb_Donation");
                });

            modelBuilder.Entity("siades.Models.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloodGroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GetPersonId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsElegilbe")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastGivenDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NextGivenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RemaingDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GetPersonId");

                    b.ToTable("Tb_Donor");
                });

            modelBuilder.Entity("siades.Models.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GetAddressId")
                        .HasColumnType("int");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GetAddressId");

                    b.ToTable("Tb_Hospital");
                });

            modelBuilder.Entity("siades.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("GetAddressId")
                        .HasColumnType("int");

                    b.Property<int?>("GetBloodId")
                        .HasColumnType("int");

                    b.Property<string>("IdentDocNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TypeIdentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContactId")
                        .IsUnique()
                        .HasFilter("[ContactId] IS NOT NULL");

                    b.HasIndex("GetAddressId");

                    b.HasIndex("GetBloodId");

                    b.ToTable("Tb_Person");
                });

            modelBuilder.Entity("siades.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeoLocation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GetCountryId")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GetCountryId");

                    b.ToTable("Tb_Province");
                });

            modelBuilder.Entity("siades.Models.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tb_Speciality");
                });

            modelBuilder.Entity("siades.Models.SpecialityDoctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GetDoctorId")
                        .HasColumnType("int");

                    b.Property<int?>("GetSpecialityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GetDoctorId");

                    b.HasIndex("GetSpecialityId");

                    b.ToTable("SpecialityDoctor");
                });

            modelBuilder.Entity("siades.Models.StockHold", b =>
                {
                    b.Property<string>("StockHoldId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StockHoldId");

                    b.HasIndex("StockHoldId")
                        .IsUnique();

                    b.ToTable("Tb_StockHold");
                });

            modelBuilder.Entity("siades.Models.TownShiep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GetProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("TownName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GetProvinceId");

                    b.ToTable("Tb_TownShiep");
                });

            modelBuilder.Entity("siades.Models.Address", b =>
                {
                    b.HasOne("siades.Models.TownShiep", "GetTownShiep")
                        .WithMany("AddressesList")
                        .HasForeignKey("GetTownShiepId");

                    b.Navigation("GetTownShiep");
                });

            modelBuilder.Entity("siades.Models.BloodRequest", b =>
                {
                    b.HasOne("siades.Models.Blood", "GetBlood")
                        .WithMany("ListRequest")
                        .HasForeignKey("GetBloodId");

                    b.HasOne("siades.Models.Donor", "GetDonor")
                        .WithMany()
                        .HasForeignKey("GetDonorId");

                    b.HasOne("siades.Models.Hospital", "GetHospital")
                        .WithMany("ListRequest")
                        .HasForeignKey("GetHospitalId");

                    b.Navigation("GetBlood");

                    b.Navigation("GetDonor");

                    b.Navigation("GetHospital");
                });

            modelBuilder.Entity("siades.Models.Doctor", b =>
                {
                    b.HasOne("siades.Models.Person", "GetPerson")
                        .WithMany("DoctorsList")
                        .HasForeignKey("GetPersonId");

                    b.Navigation("GetPerson");
                });

            modelBuilder.Entity("siades.Models.Donation", b =>
                {
                    b.HasOne("siades.Models.Donor", "GetDonor")
                        .WithMany("Donations")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GetDonor");
                });

            modelBuilder.Entity("siades.Models.Donor", b =>
                {
                    b.HasOne("siades.Models.Person", "GetPerson")
                        .WithMany("DonorsList")
                        .HasForeignKey("GetPersonId");

                    b.Navigation("GetPerson");
                });

            modelBuilder.Entity("siades.Models.Hospital", b =>
                {
                    b.HasOne("siades.Models.Address", "GetAddress")
                        .WithMany()
                        .HasForeignKey("GetAddressId");

                    b.Navigation("GetAddress");
                });

            modelBuilder.Entity("siades.Models.Person", b =>
                {
                    b.HasOne("siades.Models.Contact", "GetContact")
                        .WithOne("GetPerson")
                        .HasForeignKey("siades.Models.Person", "ContactId");

                    b.HasOne("siades.Models.Address", "GetAddress")
                        .WithMany("People")
                        .HasForeignKey("GetAddressId");

                    b.HasOne("siades.Models.Blood", "GetBlood")
                        .WithMany("People")
                        .HasForeignKey("GetBloodId");

                    b.Navigation("GetAddress");

                    b.Navigation("GetBlood");

                    b.Navigation("GetContact");
                });

            modelBuilder.Entity("siades.Models.Province", b =>
                {
                    b.HasOne("siades.Models.Country", "GetCountry")
                        .WithMany("ProvinceList")
                        .HasForeignKey("GetCountryId");

                    b.Navigation("GetCountry");
                });

            modelBuilder.Entity("siades.Models.SpecialityDoctor", b =>
                {
                    b.HasOne("siades.Models.Doctor", "GetDoctor")
                        .WithMany("Specialities")
                        .HasForeignKey("GetDoctorId");

                    b.HasOne("siades.Models.Speciality", "GetSpeciality")
                        .WithMany("Doctors")
                        .HasForeignKey("GetSpecialityId");

                    b.Navigation("GetDoctor");

                    b.Navigation("GetSpeciality");
                });

            modelBuilder.Entity("siades.Models.TownShiep", b =>
                {
                    b.HasOne("siades.Models.Province", "GetProvince")
                        .WithMany("TownShiepsList")
                        .HasForeignKey("GetProvinceId");

                    b.Navigation("GetProvince");
                });

            modelBuilder.Entity("siades.Models.Address", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("siades.Models.Blood", b =>
                {
                    b.Navigation("ListRequest");

                    b.Navigation("People");
                });

            modelBuilder.Entity("siades.Models.Contact", b =>
                {
                    b.Navigation("GetPerson");
                });

            modelBuilder.Entity("siades.Models.Country", b =>
                {
                    b.Navigation("ProvinceList");
                });

            modelBuilder.Entity("siades.Models.Doctor", b =>
                {
                    b.Navigation("Specialities");
                });

            modelBuilder.Entity("siades.Models.Donor", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("siades.Models.Hospital", b =>
                {
                    b.Navigation("ListRequest");
                });

            modelBuilder.Entity("siades.Models.Person", b =>
                {
                    b.Navigation("DoctorsList");

                    b.Navigation("DonorsList");
                });

            modelBuilder.Entity("siades.Models.Province", b =>
                {
                    b.Navigation("TownShiepsList");
                });

            modelBuilder.Entity("siades.Models.Speciality", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("siades.Models.TownShiep", b =>
                {
                    b.Navigation("AddressesList");
                });
#pragma warning restore 612, 618
        }
    }
}
